# Generated by Django 6.0 on 2025-12-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('HOME_VISIT', 'Home Visit'), ('CLINIC', 'Clinic'), ('TELECONSULT', 'Teleconsult')], default='HOME_VISIT', max_length=20),
        ),
    ]
