# Generated by Django 6.0 on 2025-12-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_encounter_encounter_type'),
        ('patients', '0002_caregiver_remove_child_guardian_child_birth_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('expected_age_months', models.IntegerField(help_text='Age in months when this milestone becomes active')),
            ],
        ),
        migrations.CreateModel(
            name='ChildMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='patients.child')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.milestonetemplate')),
            ],
            options={
                'unique_together': {('child', 'template')},
            },
        ),
    ]
