# Generated by Django 6.0 on 2025-12-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_milestonetemplate_childmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmilestone',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='milestone_evidence/'),
        ),
    ]
