# Generated by Django 6.0 on 2025-12-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_childmilestone_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmilestone',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('AI_REVIEWED', 'AI Reviewed'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
