# Generated by Django 6.0 on 2025-12-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_childmilestone_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmilestone',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
