# Generated by Django 6.0 on 2025-12-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_childmilestone_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmilestone',
            name='history',
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='title_hi',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
