# Generated by Django 6.0 on 2025-12-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0008_remove_childmilestone_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonetemplate',
            name='description_kn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='title_kn',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
