# Generated by Django 6.0 on 2025-12-15 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='developmental_videos/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='clinical.encounter')),
            ],
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('media_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='media.mediaasset')),
            ],
        ),
    ]
