# Generated by Django 6.0 on 2025-12-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
